apiVersion: apps/v1
kind: Deployment
metadata:
    name: outfit-analyzer
spec:
    replicas: 2
    selector:
        matchLabels:
            app: outfit-analyzer
    template:
        metadata:
            labels:
                app: outfit-analyzer
        spec:
            containers:
                - name: outfit-analyzer
                  image: fashionmateregistry.azurecr.io/outfit-analyzer:latest
                  ports:
                      - containerPort: 8000
                  env:
                      - name: ENVIRONMENT
                        value: "production"
                      - name: AZURE_OPENAI_ENDPOINT
                        valueFrom:
                            secretKeyRef:
                                name: azure-ai-service-secrets
                                key: AZURE_OPENAI_ENDPOINT
                      - name: AZURE_OPENAI_KEY
                        valueFrom:
                            secretKeyRef:
                                name: azure-ai-service-secrets
                                key: AZURE_OPENAI_KEY
                      - name: AZURE_SEARCH_ENDPOINT
                        valueFrom:
                            secretKeyRef:
                                name: azure-ai-service-secrets
                                key: AZURE_SEARCH_ENDPOINT
                      - name: AZURE_SEARCH_KEY
                        valueFrom:
                            secretKeyRef:
                                name: azure-ai-service-secrets
                                key: AZURE_SEARCH_KEY
                      - name: AZURE_OPENAI_COMPLETION_ENDPOINT
                        valueFrom:
                            secretKeyRef:
                                name: azure-ai-service-secrets
                                key: AZURE_OPENAI_COMPLETION_ENDPOINT
                      - name: AZURE_OPENAI_KEY
                        valueFrom:
                            secretKeyRef:
                                name: azure-ai-service-secrets
                                key: AZURE_OPENAI_KEY
                      - name: AZURE_OPENAI_DEPLOYMENT_NAME
                        valueFrom:
                            secretKeyRef:
                                name: azure-ai-service-secrets
                                key: AZURE_OPENAI_DEPLOYMENT_NAME

---
apiVersion: v1
kind: Service
metadata:
    name: outfit-analyzer-service
spec:
    type: LoadBalancer
    selector:
        app: outfit-analyzer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
