import os
import subprocess
import sys
import time

import requests

# Add the parent directory to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.code.utils import logger


def test_full_service():
    # Define the command to source the virtual environment and run app.py
    command = "python ml-backend/services/outfitAnalyzer/app.py"
    url = "http://0.0.0.0:8000/analyze"
    try:
        # Run the subprocess in the background using Popen
        process = subprocess.Popen(
            command,
            text=True,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        logger.info(f"Started process with PID {process.pid}")
        time.sleep(10)

        # Example usage
        payload = {
            "user_id": "user-1234",
            "occasion": "business meeting",
            "user_features": {
                "height_cm": 175,
                "weight_kg": 70,
                "age": 32,
                "gender": "male",
                "style": "professional",
                "body_shape": "pear",
                "body_proportion": "balanced",
                "face_shape": "oval",
                "eye_shape": "almond",
                "skin_tone": "warm",
                "hair_color": "brown",
                "face_image_url": "https://blobresource.blob.core.windows.net/user-1234/personal/face.jpg",
                "body_image_url": "https://blobresource.blob.core.windows.net/user-1234/personal/body.jpg",
                "created_at": 1710950000000,
                "updadated_at": 1710950000000,
            },
            "wardrobe": [
                {
                    "user_id": "user-1234",
                    "item_id": "item-00001",
                    "type": "Top",
                    "color": "White",
                    "pattern": "mono",
                    "fabric": "cotton",
                    "description": "White cotton button-down shirt",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00001.jpg",
                    "created_at": 1710864000000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00002",
                    "type": "Top",
                    "color": "Light Blue",
                    "pattern": "mono",
                    "fabric": "cotton",
                    "description": "Light blue oxford shirt",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00002.jpg",
                    "created_at": 1710950400000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00003",
                    "type": "Top",
                    "color": "Navy",
                    "pattern": "mono",
                    "fabric": "blend",
                    "description": "Navy blue polo shirt",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00003.jpg",
                    "created_at": 1711036800000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00004",
                    "type": "Top",
                    "color": "Black",
                    "pattern": "mono",
                    "fabric": "cashmere",
                    "description": "Black cashmere sweater",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00004.jpg",
                    "created_at": 1711123200000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00005",
                    "type": "Top",
                    "color": "Grey",
                    "pattern": "mono",
                    "fabric": "cotton",
                    "description": "Grey v-neck t-shirt",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00005.jpg",
                    "created_at": 1711209600000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00006",
                    "type": "Top",
                    "color": "Red",
                    "pattern": "mono",
                    "fabric": "linen",
                    "description": "Red linen blouse",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00006.jpg",
                    "created_at": 1711296000000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00007",
                    "type": "Top",
                    "color": "Blue",
                    "pattern": "striped",
                    "fabric": "cotton",
                    "description": "Blue striped wrap top",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00007.jpg",
                    "created_at": 1711382400000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00008",
                    "type": "Top",
                    "color": "Yellow",
                    "pattern": "mono",
                    "fabric": "blend",
                    "description": "Yellow knit sweater",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00008.jpg",
                    "created_at": 1711468800000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00009",
                    "type": "Top",
                    "color": "Blue",
                    "pattern": "mono",
                    "fabric": "denim",
                    "description": "Blue denim shirt",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00009.jpg",
                    "created_at": 1711555200000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00010",
                    "type": "Top",
                    "color": "Black",
                    "pattern": "mono",
                    "fabric": "wool",
                    "description": "Black turtleneck",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00010.jpg",
                    "created_at": 1711641600000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00011",
                    "type": "Bottom",
                    "color": "Navy",
                    "pattern": "mono",
                    "fabric": "cotton",
                    "description": "Navy chino pants",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00011.jpg",
                    "created_at": 1711728000000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00012",
                    "type": "Bottom",
                    "color": "Charcoal",
                    "pattern": "mono",
                    "fabric": "wool",
                    "description": "Charcoal dress pants",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00012.jpg",
                    "created_at": 1711814400000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00013",
                    "type": "Bottom",
                    "color": "Blue",
                    "pattern": "mono",
                    "fabric": "denim",
                    "description": "Blue jeans",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00013.jpg",
                    "created_at": 1711900800000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00014",
                    "type": "Bottom",
                    "color": "Black",
                    "pattern": "mono",
                    "fabric": "wool",
                    "description": "Black dress pants",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00014.jpg",
                    "created_at": 1711987200000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00015",
                    "type": "Bottom",
                    "color": "Khaki",
                    "pattern": "mono",
                    "fabric": "cotton",
                    "description": "Khaki chino shorts",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00015.jpg",
                    "created_at": 1712073600000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00016",
                    "type": "Outerwear",
                    "color": "Navy",
                    "pattern": "mono",
                    "fabric": "wool",
                    "description": "Navy blazer",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00016.jpg",
                    "created_at": 1712160000000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00017",
                    "type": "Outerwear",
                    "color": "Black",
                    "pattern": "mono",
                    "fabric": "leather",
                    "description": "Black leather jacket",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00017.jpg",
                    "created_at": 1712246400000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00018",
                    "type": "Outerwear",
                    "color": "Grey",
                    "pattern": "mono",
                    "fabric": "wool",
                    "description": "Grey pea coat",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00018.jpg",
                    "created_at": 1712332800000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00019",
                    "type": "Footwear",
                    "color": "Brown",
                    "pattern": "mono",
                    "fabric": "leather",
                    "description": "Brown oxford shoes",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00019.jpg",
                    "created_at": 1712419200000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00020",
                    "type": "Footwear",
                    "color": "Black",
                    "pattern": "mono",
                    "fabric": "leather",
                    "description": "Black loafers",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00020.jpg",
                    "created_at": 1712505600000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00021",
                    "type": "Footwear",
                    "color": "White",
                    "pattern": "mono",
                    "fabric": "canvas",
                    "description": "White sneakers",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00021.jpg",
                    "created_at": 1712592000000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00022",
                    "type": "Accessory",
                    "color": "Brown",
                    "pattern": "mono",
                    "fabric": "leather",
                    "description": "Brown leather belt",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00022.jpg",
                    "created_at": 1712678400000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00023",
                    "type": "Accessory",
                    "color": "Black",
                    "pattern": "mono",
                    "fabric": "leather",
                    "description": "Black leather belt",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00023.jpg",
                    "created_at": 1712764800000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00024",
                    "type": "Accessory",
                    "color": "Navy",
                    "pattern": "mono",
                    "fabric": "silk",
                    "description": "Navy silk tie",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00024.jpg",
                    "created_at": 1712851200000,
                },
                {
                    "user_id": "user-1234",
                    "item_id": "item-00025",
                    "type": "Accessory",
                    "color": "Silver",
                    "pattern": "mono",
                    "fabric": "metal",
                    "description": "Silver watch",
                    "image_url": "https://blobresource.blob.core.windows.net/user-1234/wardrobe/item-00025.jpg",
                    "created_at": 1712937600000,
                },
            ],
        }
        response = requests.post(url, json=payload)
        logger.info(response.json())

    except Exception as e:
        logger.info(f"Error starting the subprocess: {e}")


if __name__ == "__main__":
    test_full_service()
